- name: Install docker
  become: true
  hosts: all
#  gather_facts: yes
  tasks:
    - name: Update apt packages and install prerequisites
      apt:
        update_cache: yes
        upgrade: yes
    
    - name: Install prerequisites
      apt:
        name:
          - ca-certificates
          - curl
          - gpg
    
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
    
    - name: Get Debian release
      shell: (. /etc/os-release && echo "$VERSION_CODENAME")
      register: codename
    
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian {{ codename.stdout }} stable
        state: present
        filename: docker
    
    - name: Update apt and install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true
